/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminAppSheet: typeof import('./components/PublicAppSheet.vue')['default']
    AppFooter: typeof import('./components/Footer.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GlobalSnackbar: typeof import('./components/GlobalSnackbar.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Index: typeof import('./components/Index.vue')['default']
    LiricallAdmin: typeof import('./c./components/AdminAppSheet.vuefault']
    LiricallAppSheet: typeof import('./components/LiricallAppSheet.vue')['default']
    LiricallIFrameAppSheet: typeof import('./components/LiricallIFrameAppSheet.vue')['default']
    OpenPay: typeof import('./components/Payment.vue')['default']
    Payment: typeof import('./components/Payment.vue')['default']
    PublicAppSheet: typeof import('./components/PublicAppSheet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialLogin: typeof import('./components/Auth/SocialLogin.vue')['default']
  }
}
