/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Index: typeof import('./components/Index.vue')['default']
    LiricallAdmin: typeof import('./components/LiricallAdmin.vue')['default']
    LiricallAppSheet: typeof import('./components/LiricallAppSheet.vue')['default']
    LiricallIFrameAppSheet: typeof import('./components/LiricallIFrameAppSheet.vue')['default']
    OpenPay: typeof import('./components/OpenPay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
